www/config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :media_contents
    delete 'delete_media', to: "media_contents#delete_media"
    delete 'delete_all', to: 'media_contents#delete_all'
  end

  namespace :admin do
    resources :og_main_pages
  end

  namespace :admin do
    resources :stories
  end

  namespace :admin do
    resources :infos
  end

  namespace :admin do
    resources :areas
  end

  post "stores/search" => "stores#search"

  get "home/translate" => "home#translate"

  resources :brands
  resources :abouts
  resources :contacts
  resources :news
  resources :stores
  resources :subscribes
  resources :products
  resources :inspections
  mount Ckeditor::Engine => '/ckeditor'

  namespace :admin do
    root 'home#index'
    resources :site_configs
    resources :site_config_images
    resources :contacts
    resources :news
    resources :brands
    resources :products
    resources :images
    resources :histories
    resources :abouts
    resources :staffs
    resources :stores
    resources :subscribes
    resources :subproducts
  end

  get "home/new_verification" => "home#new_verification"
  post "home/verification" => "home#verification"
  get 'home/terms_of_service'
  get 'home/privacy_policy'
  devise_for :users

  get "brand/:url_name" => "brands#show"
  get "product/:url_name" => "products#show"

  root 'home#index'

end

www/app/models/admin/og_main_page.rb
class Admin::OgMainPage < ActiveRecord::Base
	mount_uploader :home_image, ImageUploader
	mount_uploader :home_image2, ImageUploader
	mount_uploader :home_image3, ImageUploader
	mount_uploader :about_image, ImageUploader
	mount_uploader :about_image2, ImageUploader
	mount_uploader :about_image3, ImageUploader
	mount_uploader :contact_image, ImageUploader
	mount_uploader :contact_image2, ImageUploader
	mount_uploader :contact_image3, ImageUploader
	mount_uploader :store_image, ImageUploader
	mount_uploader :store_image2, ImageUploader
	mount_uploader :store_image3, ImageUploader
	mount_uploader :news_image, ImageUploader
	mount_uploader :news_image2, ImageUploader
	mount_uploader :news_image3, ImageUploader
	mount_uploader :brand_image, ImageUploader
	mount_uploader :brand_image2, ImageUploader
	mount_uploader :brand_image3, ImageUploader
end

www/app/controllers/admin/og_main_pages_controller.rb
class Admin::OgMainPagesController < Admin::ApplicationController
  before_action :set_admin_og_main_page, only: [:show, :update, :destroy]

  # GET /admin/og_main_pages
  # GET /admin/og_main_pages.json
  def index
    @admin_og_main_pages = Admin::OgMainPage.all
  end

  # GET /admin/og_main_pages/1
  # GET /admin/og_main_pages/1.json
  def show
  end

  # GET /admin/og_main_pages/new
  def new
    @admin_og_main_page = Admin::OgMainPage.new
  end

  # GET /admin/og_main_pages/1/edit
  def edit
    if Admin::OgMainPage.where(params[:id]).present?
      @admin_og_main_page = Admin::OgMainPage.find(params[:id])
    else
      @admin_og_main_page = Admin::OgMainPage.create(:id => 1)
    end
  end

  # POST /admin/og_main_pages
  # POST /admin/og_main_pages.json
  def create
    @admin_og_main_page = Admin::OgMainPage.new(admin_og_main_page_params)

    respond_to do |format|
      if @admin_og_main_page.save
        format.html { redirect_to @admin_og_main_page, notice: 'Og main page was successfully created.' }
        format.json { render :show, status: :created, location: @admin_og_main_page }
      else
        format.html { render :new }
        format.json { render json: @admin_og_main_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/og_main_pages/1
  # PATCH/PUT /admin/og_main_pages/1.json
  def update
    respond_to do |format|
      if @admin_og_main_page.update(admin_og_main_page_params)
        format.html { redirect_to edit_admin_og_main_page_path, notice: 'OG管理更新成功' }
        format.json { render :show, status: :ok, location: @admin_og_main_page }
      else
        format.html { render :edit }
        format.json { render json: @admin_og_main_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/og_main_pages/1
  # DELETE /admin/og_main_pages/1.json
  def destroy
    @admin_og_main_page.destroy
    respond_to do |format|
      format.html { redirect_to admin_og_main_pages_url, notice: 'Og main page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_og_main_page
      @admin_og_main_page = Admin::OgMainPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_og_main_page_params
      params.require(:admin_og_main_page).permit(:home_title, :home_description, :home_image, :home_image2, :home_image3, :about_title, :about_description, :about_image, :about_image2, :about_image3, :contact_title, :contact_description, :contact_image, :contact_image2, :contact_image3, :store_title, :store_description, :store_image, :store_image2, :store_image3, :news_title, :news_description, :news_image, :news_image2, :news_image3, :brand_title, :brand_description, :brand_image, :brand_image2, :brand_image3)
    end
end

www/app/helpers/admin/og_main_pages_helper.rb
module Admin::OgMainPagesHelper
end

www/app/views/admin/og_main_pages/_form.html.erb
<%= form_for(@admin_og_main_page) do |f| %>
  <% if @admin_og_main_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_og_main_page.errors.count, "error") %> prohibited this admin_og_main_page from being saved:</h2>

      <ul>
      <% @admin_og_main_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br />
  <h3>Home</h3>
  <div class="form-group">
    <%= f.label :home_title, 'Home_OG標題' %><br>
    <%= f.text_field :home_title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :home_description, 'Home_OG內容' %><br>
    <%= f.text_area :home_description, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :home_image, 'Home_OG主視覺 (2:1) (1200 * 628)' %><br>
    <%= image_tag(@admin_og_main_page.home_image.thumb.url) %>
    <%= f.file_field :home_image %>
  </div>
  <div class="form-group">
    <%= f.label :home_image2, 'Home_OG主視覺2 (2:1) (1200 * 628)' %><br>
    <%= image_tag(@admin_og_main_page.home_image2.thumb.url) %>
    <%= f.file_field :home_image2 %>
  </div>
  <div class="form-group">
    <%= f.label :home_image3, 'Home_OG主視覺3 (2:1) (1200 * 628)' %><br>
    <%= image_tag(@admin_og_main_page.home_image3.thumb.url) %>
    <%= f.file_field :home_image3 %>
  </div>


  <br />
  <br />
  <h3>About</h3>
  <div class="form-group">
    <%= f.label :about_title, 'About_OG標題' %><br>
    <%= f.text_field :about_title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :about_description, 'About_OG內容' %><br>
    <%= f.text_area :about_description, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :about_image, 'About_OG主視覺 (2:1) (1200 * 628)' %><br>
    <%= image_tag(@admin_og_main_page.about_image.thumb.url) %>
    <%= f.file_field :about_image %>
  </div>
  <div class="form-group">
    <%= f.label :about_image2, 'About_OG主視覺2 (2:1) (1200 * 628)' %><br>
    <%= image_tag(@admin_og_main_page.about_image2.thumb.url) %>
    <%= f.file_field :about_image2 %>
  </div>
  <div class="form-group">
    <%= f.label :about_image3, 'About_OG主視覺3 (2:1) (1200 * 628)' %><br>
    <%= image_tag(@admin_og_main_page.about_image3.thumb.url) %>
    <%= f.file_field :about_image3 %>
  </div>


  <br />
  <br />
  <h3>Contact</h3>
  <div class="form-group">
    <%= f.label :contact_title, 'Contact_OG標題' %><br>
    <%= f.text_field :contact_title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :contact_description, 'Contact_OG內容' %><br>
    <%= f.text_area :contact_description, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :contact_image, 'Contact_OG主視覺 (2:1) (1200 * 628)' %><br>
    <%= image_tag(@admin_og_main_page.contact_image.thumb.url) %>
    <%= f.file_field :contact_image %>
  </div>
  <div class="form-group">
    <%= f.label :contact_image2, 'Contact_OG主視覺2 (2:1) (1200 * 628)' %><br>
    <%= image_tag(@admin_og_main_page.contact_image2.thumb.url) %>
    <%= f.file_field :contact_image2 %>
  </div>
  <div class="form-group">
    <%= f.label :contact_image3, 'Contact_OG主視覺3 (2:1) (1200 * 628)' %><br>
    <%= image_tag(@admin_og_main_page.contact_image3.thumb.url) %>
    <%= f.file_field :contact_image3 %>
  </div>


  <br />
  <br />
  <h3>Store</h3>
  <div class="form-group">
    <%= f.label :store_title, 'Store_OG標題' %><br>
    <%= f.text_field :store_title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :store_description, 'Store_OG內容' %><br>
    <%= f.text_area :store_description, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :store_image, 'STORE_OG主視覺 (2:1) (1200 * 628)' %><br>
    <%= image_tag(@admin_og_main_page.store_image.thumb.url) %>
    <%= f.file_field :store_image %>
  </div>
  <div class="form-group">
    <%= f.label :store_image2, 'STORE_OG主視覺2 (2:1) (1200 * 628)' %><br>
    <%= image_tag(@admin_og_main_page.store_image2.thumb.url) %>
    <%= f.file_field :store_image2 %>
  </div>
  <div class="form-group">
    <%= f.label :store_image3, 'STORE_OG主視覺3 (2:1) (1200 * 628)' %><br>
    <%= image_tag(@admin_og_main_page.store_image3.thumb.url) %>
    <%= f.file_field :store_image3 %>
  </div>


  <br />
  <br />
  <h3>News</h3>
  <div class="form-group">
    <%= f.label :news_title, 'News_OG標題' %><br>
    <%= f.text_field :news_title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :news_description, 'News_OG內容' %><br>
    <%= f.text_area :news_description, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :news_image, 'News_OG主視覺 (2:1) (1200 * 628)' %><br>
    <%= image_tag(@admin_og_main_page.news_image.thumb.url) %>
    <%= f.file_field :news_image %>
  </div>
  <div class="form-group">
    <%= f.label :news_image2, 'News_OG主視覺2 (2:1) (1200 * 628)' %><br>
    <%= image_tag(@admin_og_main_page.news_image2.thumb.url) %>
    <%= f.file_field :news_image2 %>
  </div>
  <div class="form-group">
    <%= f.label :news_image3, 'News_OG主視覺3 (2:1) (1200 * 628)' %><br>
    <%= image_tag(@admin_og_main_page.news_image3.thumb.url) %>
    <%= f.file_field :news_image3 %>
  </div>


  <br />
  <br />
  <h3>Brand</h3>
  <div class="form-group">
    <%= f.label :brand_title, 'Brand_OG標題' %><br>
    <%= f.text_field :brand_title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :brand_description, 'Brand_OG內容' %><br>
    <%= f.text_area :brand_description, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :brand_image, 'Brand_OG主視覺 (2:1) (1200 * 628)' %><br>
    <%= image_tag(@admin_og_main_page.brand_image.thumb.url) %>
    <%= f.file_field :brand_image %>
  </div>
  <div class="form-group">
    <%= f.label :brand_image2, 'Brand_OG主視覺2 (2:1) (1200 * 628)' %><br>
    <%= image_tag(@admin_og_main_page.brand_image2.thumb.url) %>
    <%= f.file_field :brand_image2 %>
  </div>
  <div class="form-group">
    <%= f.label :brand_image3, 'Brand_OG主視覺3 (2:1) (1200 * 628)' %><br>
    <%= image_tag(@admin_og_main_page.brand_image3.thumb.url) %>
    <%= f.file_field :brand_image3 %>
  </div>

  <br />
  <div class="actions">
    <%= f.submit 'OG 更新', :class => "btn btn-primary btn-full" %>
  </div>
<% end %>

www/app/views/admin/og_main_pages/edit.html.erb
<h1>OG管理</h1>

<%= render 'form' %>

<%#= link_to 'Show', @admin_og_main_page %>
<%#= link_to 'Back', admin_og_main_pages_path %>

www/app/views/admin/og_main_pages/index.html.erb
<h1>Listing admin_og_main_pages</h1>

<table>
  <thead>
    <tr>
      <th>Home title</th>
      <th>Home description</th>
      <th>Home image</th>
      <th>About title</th>
      <th>About description</th>
      <th>About image</th>
      <th>Contact title</th>
      <th>Contact description</th>
      <th>Contact image</th>
      <th>Store title</th>
      <th>Store description</th>
      <th>Store image</th>
      <th>News title</th>
      <th>News description</th>
      <th>News image</th>
      <th>Brand title</th>
      <th>Brand description</th>
      <th>Brand image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_og_main_pages.each do |admin_og_main_page| %>
      <tr>
        <td><%= admin_og_main_page.home_title %></td>
        <td><%= admin_og_main_page.home_description %></td>
        <td><%= admin_og_main_page.home_image %></td>
        <td><%= admin_og_main_page.about_title %></td>
        <td><%= admin_og_main_page.about_description %></td>
        <td><%= admin_og_main_page.about_image %></td>
        <td><%= admin_og_main_page.contact_title %></td>
        <td><%= admin_og_main_page.contact_description %></td>
        <td><%= admin_og_main_page.contact_image %></td>
        <td><%= admin_og_main_page.store_title %></td>
        <td><%= admin_og_main_page.store_description %></td>
        <td><%= admin_og_main_page.store_image %></td>
        <td><%= admin_og_main_page.news_title %></td>
        <td><%= admin_og_main_page.news_description %></td>
        <td><%= admin_og_main_page.news_image %></td>
        <td><%= admin_og_main_page.brand_title %></td>
        <td><%= admin_og_main_page.brand_description %></td>
        <td><%= admin_og_main_page.brand_image %></td>
        <td><%= link_to 'Show', admin_og_main_page %></td>
        <td><%= link_to 'Edit', edit_admin_og_main_page_path(admin_og_main_page) %></td>
        <td><%= link_to 'Destroy', admin_og_main_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Og main page', new_admin_og_main_page_path %>

www/app/views/admin/og_main_pages/new.html.erb
<h1>New admin_og_main_page</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_og_main_pages_path %>

www/app/views/admin/og_main_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Home title:</strong>
  <%= @admin_og_main_page.home_title %>
</p>

<p>
  <strong>Home description:</strong>
  <%= @admin_og_main_page.home_description %>
</p>

<p>
  <strong>Home image:</strong>
  <%= @admin_og_main_page.home_image %>
</p>

<p>
  <strong>About title:</strong>
  <%= @admin_og_main_page.about_title %>
</p>

<p>
  <strong>About description:</strong>
  <%= @admin_og_main_page.about_description %>
</p>

<p>
  <strong>About image:</strong>
  <%= @admin_og_main_page.about_image %>
</p>

<p>
  <strong>Contact title:</strong>
  <%= @admin_og_main_page.contact_title %>
</p>

<p>
  <strong>Contact description:</strong>
  <%= @admin_og_main_page.contact_description %>
</p>

<p>
  <strong>Contact image:</strong>
  <%= @admin_og_main_page.contact_image %>
</p>

<p>
  <strong>Store title:</strong>
  <%= @admin_og_main_page.store_title %>
</p>

<p>
  <strong>Store description:</strong>
  <%= @admin_og_main_page.store_description %>
</p>

<p>
  <strong>Store image:</strong>
  <%= @admin_og_main_page.store_image %>
</p>

<p>
  <strong>News title:</strong>
  <%= @admin_og_main_page.news_title %>
</p>

<p>
  <strong>News description:</strong>
  <%= @admin_og_main_page.news_description %>
</p>

<p>
  <strong>News image:</strong>
  <%= @admin_og_main_page.news_image %>
</p>

<p>
  <strong>Brand title:</strong>
  <%= @admin_og_main_page.brand_title %>
</p>

<p>
  <strong>Brand description:</strong>
  <%= @admin_og_main_page.brand_description %>
</p>

<p>
  <strong>Brand image:</strong>
  <%= @admin_og_main_page.brand_image %>
</p>

<%= link_to 'Edit', edit_admin_og_main_page_path(@admin_og_main_page) %> |
<%= link_to 'Back', admin_og_main_pages_path %>