www/config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :media_contents
    delete 'delete_media', to: "media_contents#delete_media"
    delete 'delete_all', to: 'media_contents#delete_all'
  end

  namespace :admin do
    resources :og_main_pages
  end

  namespace :admin do
    resources :stories
  end

  namespace :admin do
    resources :infos
  end

  namespace :admin do
    resources :areas
  end

  post "stores/search" => "stores#search"

  get "home/translate" => "home#translate"

  resources :brands
  resources :abouts
  resources :contacts
  resources :news
  resources :stores
  resources :subscribes
  resources :products
  resources :inspections
  mount Ckeditor::Engine => '/ckeditor'

  namespace :admin do
    root 'home#index'
    resources :site_configs
    resources :site_config_images
    resources :contacts
    resources :news
    resources :brands
    resources :products
    resources :images
    resources :histories
    resources :abouts
    resources :staffs
    resources :stores
    resources :subscribes
    resources :subproducts
  end

  get "home/new_verification" => "home#new_verification"
  post "home/verification" => "home#verification"
  get 'home/terms_of_service'
  get 'home/privacy_policy'
  devise_for :users

  get "brand/:url_name" => "brands#show"
  get "product/:url_name" => "products#show"

  root 'home#index'

end

www/app/models/admin/staff.rb
class Admin::Staff < ActiveRecord::Base
	mount_uploader :photo, ImageUploader
	belongs_to :about
end

www/app/controllers/admin/staffs_controller.rb
class Admin::StaffsController < Admin::ApplicationController
  before_action :set_admin_staff, only: [:show, :edit, :update, :destroy]

  # GET /admin/staffs
  # GET /admin/staffs.json
  def index
    @admin_staffs = Admin::Staff.all
  end

  # GET /admin/staffs/1
  # GET /admin/staffs/1.json
  def show
  end

  # GET /admin/staffs/new
  def new
    @admin_staff = Admin::Staff.new
  end

  # GET /admin/staffs/1/edit
  def edit
  end

  # POST /admin/staffs
  # POST /admin/staffs.json
  def create
    @admin_staff = Admin::Staff.new(admin_staff_params)

    respond_to do |format|
      if @admin_staff.save
        format.html { redirect_to @admin_staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @admin_staff }
      else
        format.html { render :new }
        format.json { render json: @admin_staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/staffs/1
  # PATCH/PUT /admin/staffs/1.json
  def update
    respond_to do |format|
      if @admin_staff.update(admin_staff_params)
        format.html { redirect_to @admin_staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_staff }
      else
        format.html { render :edit }
        format.json { render json: @admin_staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/staffs/1
  # DELETE /admin/staffs/1.json
  def destroy
    @admin_staff.destroy
    respond_to do |format|
      format.html { redirect_to admin_staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_staff
      @admin_staff = Admin::Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_staff_params
      params.require(:admin_staff).permit(:name, :office, :slogan, :content, :about_id, :slogan2, :photo)
    end
end

www/app/helpers/admin/staffs_helper.rb
module Admin::StaffsHelper
end

www/app/views/admin/staffs/_form.html.erb
<%= form_for(@admin_staff) do |f| %>
  <% if @admin_staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_staff.errors.count, "error") %> prohibited this admin_staff from being saved:</h2>

      <ul>
      <% @admin_staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :office %><br>
    <%= f.text_field :office %>
  </div>
  <div class="field">
    <%= f.label :slogan %><br>
    <%= f.text_field :slogan %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :about_id %><br>
    <%= f.number_field :about_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

www/app/views/admin/staffs/edit.html.erb
<h1>Editing admin_staff</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_staff %> |
<%= link_to 'Back', admin_staffs_path %>

www/app/views/admin/staffs/index.html.erb
<h1>Listing admin_staffs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Office</th>
      <th>Slogan</th>
      <th>Content</th>
      <th>About</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_staffs.each do |admin_staff| %>
      <tr>
        <td><%= admin_staff.name %></td>
        <td><%= admin_staff.office %></td>
        <td><%= admin_staff.slogan %></td>
        <td><%= admin_staff.content %></td>
        <td><%= admin_staff.about_id %></td>
        <td><%= link_to 'Show', admin_staff %></td>
        <td><%= link_to 'Edit', edit_admin_staff_path(admin_staff) %></td>
        <td><%= link_to 'Destroy', admin_staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_admin_staff_path %>

www/app/views/admin/staffs/new.html.erb
<h1>New admin_staff</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_staffs_path %>

www/app/views/admin/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_staff.name %>
</p>

<p>
  <strong>Office:</strong>
  <%= @admin_staff.office %>
</p>

<p>
  <strong>Slogan:</strong>
  <%= @admin_staff.slogan %>
</p>

<p>
  <strong>Content:</strong>
  <%= @admin_staff.content %>
</p>

<p>
  <strong>About:</strong>
  <%= @admin_staff.about_id %>
</p>

<%= link_to 'Edit', edit_admin_staff_path(@admin_staff) %> |
<%= link_to 'Back', admin_staffs_path %>