www/config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :media_contents
    delete 'delete_media', to: "media_contents#delete_media"
    delete 'delete_all', to: 'media_contents#delete_all'
  end

  namespace :admin do
    resources :og_main_pages
  end

  namespace :admin do
    resources :stories
  end

  namespace :admin do
    resources :infos
  end

  namespace :admin do
    resources :areas
  end

  post "stores/search" => "stores#search"

  get "home/translate" => "home#translate"

  resources :brands
  resources :abouts
  resources :contacts
  resources :news
  resources :stores
  resources :subscribes
  resources :products
  resources :inspections
  mount Ckeditor::Engine => '/ckeditor'

  namespace :admin do
    root 'home#index'
    resources :site_configs
    resources :site_config_images
    resources :contacts
    resources :news
    resources :brands
    resources :products
    resources :images
    resources :histories
    resources :abouts
    resources :staffs
    resources :stores
    resources :subscribes
    resources :subproducts
  end

  get "home/new_verification" => "home#new_verification"
  post "home/verification" => "home#verification"
  get 'home/terms_of_service'
  get 'home/privacy_policy'
  devise_for :users

  get "brand/:url_name" => "brands#show"
  get "product/:url_name" => "products#show"

  root 'home#index'

end

www/app/models/admin/site_config.rb
class Admin::SiteConfig < ActiveRecord::Base
	has_many :site_config_images , dependent: :destroy
	has_many :images ,  :through => :site_config_images

	def get_phone_images
		self.images.where(:admin_site_config_images => {:is_phone => true}).order('admin_site_config_images.sort')
	end

	def get_pc_images
		self.images.where(:admin_site_config_images => {:is_phone => false}).order('admin_site_config_images.sort')
	end

	def get_email
		if self.email.present?
			self.email
		else
			"direct.service.13@gmail.com"
		end
	end
end

www/app/controllers/admin/site_configs_controller.rb
class Admin::SiteConfigsController < Admin::ApplicationController
  before_action :set_admin_site_config, only: [:show, :edit, :update, :destroy]

  # GET /admin/site_configs
  # GET /admin/site_configs.json
  def index
    @admin_site_configs = Admin::SiteConfig.all
  end

  # GET /admin/site_configs/1
  # GET /admin/site_configs/1.json
  def show
  end

  # GET /admin/site_configs/new
  def new
    @admin_site_config = Admin::SiteConfig.new
  end

  # GET /admin/site_configs/1/edit
  def edit
  end

  # POST /admin/site_configs
  # POST /admin/site_configs.json
  def create
    # @admin_site_config = Admin::SiteConfig.new(admin_site_config_params)

    # respond_to do |format|
    #   if @admin_site_config.save
    #     format.html { redirect_to @admin_site_config, notice: 'Site config was successfully created.' }
    #     format.json { render :show, status: :created, location: @admin_site_config }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @admin_site_config.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /admin/site_configs/1
  # PATCH/PUT /admin/site_configs/1.json
  def update
    respond_to do |format|
      if @admin_site_config.update(admin_site_config_params)
        format.html { redirect_to edit_admin_site_config_path, notice: '網站管理更新成功' }
        format.json { render :show, status: :ok, location: @admin_site_config }
      else
        format.html { render :edit }
        format.json { render json: @admin_site_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/site_configs/1
  # DELETE /admin/site_configs/1.json
  def destroy
    @admin_site_config.destroy
    respond_to do |format|
      format.html { redirect_to admin_site_configs_url, notice: 'Site config was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_site_config
      @admin_site_config = Admin::SiteConfig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_site_config_params
      params.require(:admin_site_config).permit(:title, :description, :name, :tax_id, :phone, :fax, :address, :email, :website_url, :facebook_url, :main_visual_logo_is_show, :brands_list_logo_is_show, :slide_speed, :privacy_policy, :terms_of_service)
    end
end

www/app/helpers/admin/site_configs_helper.rb
module Admin::SiteConfigsHelper
end

www/app/views/admin/site_configs/_form.html.erb
<%= form_for(@admin_site_config) do |f| %>
  <% if @admin_site_config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_site_config.errors.count, "error") %> prohibited this admin_site_config from being saved:</h2>

      <ul>
      <% @admin_site_config.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, '標題 ( Meta_Title ) ' %><br>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description, '內容 ( Meta_Description ) ' %><br>
    <%#= f.cktext_area :description, :ckeditor => {:toolbar => 'mini'} %>
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label '公司名稱' %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label '統一編號' %><br>
    <%= f.text_field :tax_id, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label '電話號碼' %><br>
    <%= f.text_field :phone, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label '傳真號碼' %><br>
    <%= f.text_field :fax, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label '地址' %><br>
    <%= f.text_field :address, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email,'電子郵件(聯絡我們收信信箱)' %><br>
    <%= f.text_field :email, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label '網站網址' %><br>
    <%= f.text_field :website_url, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label 'FB網址' %><br>
    <%= f.text_field :facebook_url, :class => "form-control" %>
  </div>


  <div class="form-group">
    <%= f.label '主視覺LOGO是否顯示' %><br>
    <%= f.check_box :main_visual_logo_is_show %>
  </div>
  <div class="form-group">
    <%= f.label '品牌列LOGO是否顯示' %><br>
    <%= f.check_box :brands_list_logo_is_show %>
  </div>

  <div class="form-group">
    <%= f.label :slide_speed, '輪播速度 -- 1000 = 1秒 最少3000' %><br>
    <%= f.number_field :slide_speed, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :privacy_policy, '隱私政策' %><br>
    <%= f.cktext_area :privacy_policy, :ckeditor => {:toolbar => 'mini'} %>
    <%#= f.text_area :privacy_policy, :class => "form-control" %>
  </div>  
  <div class="form-group">
    <%= f.label :terms_of_service, '服務條款' %><br>
    <%= f.cktext_area :terms_of_service, :ckeditor => {:toolbar => 'mini'} %>
    <%#= f.text_area :terms_of_service, :class => "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit '網站管理 更新', :class => "btn btn-primary btn-full" %>
  </div>
<% end %>

www/app/views/admin/site_configs/_phone_uploader.html.erb
<div class="fileupload_wrapper">
  <article>
    <%= form_for Admin::Image.new, :html => { :id => "admin_phone_image_file", :multipart => true} do |f| %>
      <div class='btn btn-success' style="width: 100%;">
        <h1 class='upload_button_h1'>手機 主視覺 - 選擇檔案或者拖曳至此上傳</h1>
        <%= hidden_field_tag 'site_config_id', @admin_site_config.id %>
        <%= f.file_field :file, :class=>'file_field' %>
        <%= hidden_field_tag 'is_phone', true %>
      </div>
    <% end %>

    <div id="progress_phone" class="progress_phone">
      <div class="progress_phone-bar progress_phone-bar-success"></div>
    </div>

    <table class='phone_image_uploder_table table'>
          <tr align="center">
            <td>圖片</td>
            <td>檔案名稱</td>
            <td></td>
          </tr>
          
          <tr align="center" class='hide phone_image_tr'>
              <td>
                <img class="tmp_image" src="" data-id='0'>
              </td>
              <td>
                <h6>tmp</h6>
              </td>
              <td class='phone_image_delete'>
                <%= link_to 'Delete', '#', :id=>'delete', :class => 'delete btn btn-danger'  %>
              </td>
          </tr>


      
            <% if @admin_site_config.images.count>0 %>

                  <% @admin_site_config.site_config_images.where(:is_phone => true).order(:sort).each do |site_config_image| %>
                    <% file = site_config_image.image %>
                    <tr align="center" class='phone_image_tr'>
                        <td>
                          <%= form_for file.site_config_image, :remote => true do |f| %>
                            <%= f.hidden_field :sort %>
                          <% end %>
                          <%= image_tag(file.file.small.url, :data => { :id => file.id }) %>
                        </td>
                        <td><%= file.file.file.filename %></td>
                        <td>
                          <%= link_to 'Delete', admin_image_path(file, :format => :json), :class => 'delete btn btn-danger', method: :delete,:remote=>true %>
                        </td>
                    </tr>
                  <% end %>


            <% end %>


        </table>
      </article>
  </div>

  <script type="text/javascript">

    (function() {
      $(function() {
        $('.progress_phone').hide();
        return $('#admin_phone_image_file').fileupload({
          dropZone: $('#admin_phone_image_file'),
          dataType: 'json',
          done: function(e, data) {
            return $.each(data.result.files, function(index, file) {
              var list;
              list = $('.hide.phone_image_tr').clone();
              list.find('img').attr('src', file.small_url);
              list.find('img').attr('data-id', file.id);
              list.find('h6').text(file.name);
              list.find('.phone_image_delete a').attr('data-method', file.delete_type).attr('href', file.delete_url).attr('data-remote', true);
              list.removeClass('hide').appendTo('.phone_image_uploder_table');
              $('.progress_phone .progress_phone-bar').css('width', "0%");
              return $('.progress_phone').hide();
            });
          },
          progressall: function(e, data) {
            var progress_phone;
            $('.progress_phone').show();
            $('.progress_phone .progress_phone-bar').css('height', "100%");
            progress_phone = parseInt(data.loaded / data.total * 100, 10);
            console.log(progress_phone);
            return $('.progress_phone .progress_phone-bar').css('width', progress_phone + "%");
          },
          error: function(e, data) {
            return alert("檔案上傳失敗");
          }
        });
      });

    }).call(this);





      

    $( document ).ready(function() {

      $('.phone_image_uploder_table').sortable({ 
        items: "tr:not(:first-child)",
        sort: function( event, ui ){
          ui.item.find('td').addClass('sorting');
        },
        stop: function( event, ui ){
          ui.item.find('td').removeClass('sorting')
        },
        update: function( event, ui ) {
          var site_config_image = $(this);
          $(site_config_image).find('tr').each(function(){
            $(this).find('#admin_site_config_image_sort').val($(this).index() - 2);
          });
          $('.loading').find('p').text('Sorting...');
          $('.loading').show(0);
          setTimeout(function(){
            $(site_config_image).find('form').each(function(){
              $(this).submit();
            });
            $(site_config_image).find('form').last().bind("ajax:complete", function(xhr, status) {
              $('.loading').find('p').text('Sorted');
              $('.loading').fadeOut(800);
            });
          }, 800);
        }
      });

      $.ajaxSettings.dataType = "json";
      $(document).delegate('a.delete', 'ajax:complete', function(xhr, status){
        if(status.responseText=='success'){
          $(this).parents('.phone_image_tr').remove();
        }
      });

    });

  </script>

www/app/views/admin/site_configs/_uploader.html.erb
<div class="fileupload_wrapper">
  <article>
    <%= form_for Admin::Image.new, :html => { :multipart => true} do |f| %>
      <div class='btn btn-success' style="width: 100%;">
        <h1 class='upload_button_h1'>電腦 主視覺 - 選擇檔案或者拖曳至此上傳</h1>
        <%= hidden_field_tag 'site_config_id', @admin_site_config.id %>
        <%= f.file_field :file, :class=>'file_field' %>
      </div>
    <% end %>

    <div id="progress" class="progress">
      <div class="progress-bar progress-bar-success"></div>
    </div>

    <table class='image_uploder_table table'>
          <tr align="center">
            <td>圖片</td>
            <td>檔案名稱</td>
            <td></td>
          </tr>
          
          <tr align="center" class='hide image_tr'>
              <td>
                <img class="tmp_image" src="" data-id='0'>
              </td>
              <td>
                <h6>tmp</h6>
              </td>
              <td class='image_delete'>
                <%= link_to 'Delete', '#', :id=>'delete', :class => 'delete btn btn-danger'  %>
              </td>
          </tr>


      
            <% if @admin_site_config.images.count>0 %>

                  <% @admin_site_config.site_config_images.where(:is_phone => false).order(:sort).each do |site_config_image| %>
                    <% file = site_config_image.image %>
                    <tr align="center" class='image_tr'>
                        <td>
                          <%= form_for file.site_config_image, :remote => true do |f| %>
                            <%= f.hidden_field :sort %>
                          <% end %>
                          <%= image_tag(file.file.small.url, :data => { :id => file.id }) %>
                        </td>
                        <td><%= file.file.file.filename %></td>
                        <td>
                          <%= link_to 'Delete', admin_image_path(file, :format => :json), :class => 'delete btn btn-danger', method: :delete,:remote=>true %>
                        </td>
                    </tr>
                  <% end %>


            <% end %>


        </table>
      </article>
  </div>

  <script type="text/javascript">

    (function() {
      $(function() {
        $('.progress').hide();
        return $('#admin_image_file').fileupload({
          dropZone: $('#admin_image_file'),
          dataType: 'json',
          done: function(e, data) {
            return $.each(data.result.files, function(index, file) {
              var list;
              list = $('.hide.image_tr').clone();
              list.find('img').attr('src', file.small_url);
              list.find('img').attr('data-id', file.id);
              list.find('h6').text(file.name);
              list.find('.image_delete a').attr('data-method', file.delete_type).attr('href', file.delete_url).attr('data-remote', true);
              list.removeClass('hide').appendTo('.image_uploder_table');
              $('.progress .progress-bar').css('width', "0%");
              return $('.progress').hide();
            });
          },
          progressall: function(e, data) {
            var progress;
            $('.progress').show();
            $('.progress .progress-bar').css('height', "100%");
            progress = parseInt(data.loaded / data.total * 100, 10);
            console.log(progress);
            return $('.progress .progress-bar').css('width', progress + "%");
          },
          error: function(e, data) {
            return alert("檔案上傳失敗");
          }
        });
      });

    }).call(this);





      

    $( document ).ready(function() {

      $('.image_uploder_table').sortable({ 
        items: "tr:not(:first-child)",
        sort: function( event, ui ){
          ui.item.find('td').addClass('sorting');
        },
        stop: function( event, ui ){
          ui.item.find('td').removeClass('sorting')
        },
        update: function( event, ui ) {
          var site_config_image = $(this);
          $(site_config_image).find('tr').each(function(){
            $(this).find('#admin_site_config_image_sort').val($(this).index() - 2);
          });
          $('.loading').find('p').text('Sorting...');
          $('.loading').show(0);
          setTimeout(function(){
            $(site_config_image).find('form').each(function(){
              $(this).submit();
            });
            $(site_config_image).find('form').last().bind("ajax:complete", function(xhr, status) {
              $('.loading').find('p').text('Sorted');
              $('.loading').fadeOut(800);
            });
          }, 800);
        }
      });

      $.ajaxSettings.dataType = "json";
      $(document).delegate('a.delete', 'ajax:complete', function(xhr, status){
        if(status.responseText=='success'){
          $(this).parents('.image_tr').remove();
        }
      });

    });

  </script>

www/app/views/admin/site_configs/edit.html.erb
<h1>網站管理</h1>

<%= render 'form' %>

<%= render :partial => 'uploader' %>

<%= render :partial => 'phone_uploader' %>
<%#= link_to 'Show', @admin_site_config %>
<%#= link_to 'Back', admin_site_configs_path %>

www/app/views/admin/site_configs/index.html.erb
<h1>Listing admin_site_configs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Name</th>
      <th>Tax</th>
      <th>Phone</th>
      <th>Fax</th>
      <th>Address</th>
      <th>Email</th>
      <th>Website url</th>
      <th>Facebook url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_site_configs.each do |admin_site_config| %>
      <tr>
        <td><%= admin_site_config.title %></td>
        <td><%= admin_site_config.description %></td>
        <td><%= admin_site_config.name %></td>
        <td><%= admin_site_config.tax_id %></td>
        <td><%= admin_site_config.phone %></td>
        <td><%= admin_site_config.fax %></td>
        <td><%= admin_site_config.address %></td>
        <td><%= admin_site_config.email %></td>
        <td><%= admin_site_config.website_url %></td>
        <td><%= admin_site_config.facebook_url %></td>
        <td><%= link_to 'Show', admin_site_config %></td>
        <td><%= link_to 'Edit', edit_admin_site_config_path(admin_site_config) %></td>
        <td><%= link_to 'Destroy', admin_site_config, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site config', new_admin_site_config_path %>

www/app/views/admin/site_configs/new.html.erb
<h1>New admin_site_config</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_site_configs_path %>

www/app/views/admin/site_configs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @admin_site_config.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_site_config.description %>
</p>

<p>
  <strong>Name:</strong>
  <%= @admin_site_config.name %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @admin_site_config.tax_id %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @admin_site_config.phone %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @admin_site_config.fax %>
</p>

<p>
  <strong>Address:</strong>
  <%= @admin_site_config.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin_site_config.email %>
</p>

<p>
  <strong>Website url:</strong>
  <%= @admin_site_config.website_url %>
</p>

<p>
  <strong>Facebook url:</strong>
  <%= @admin_site_config.facebook_url %>
</p>

<%= link_to 'Edit', edit_admin_site_config_path(@admin_site_config) %> |
<%= link_to 'Back', admin_site_configs_path %>