www/config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :media_contents
    delete 'delete_media', to: "media_contents#delete_media"
    delete 'delete_all', to: 'media_contents#delete_all'
  end

  namespace :admin do
    resources :og_main_pages
  end

  namespace :admin do
    resources :stories
  end

  namespace :admin do
    resources :infos
  end

  namespace :admin do
    resources :areas
  end

  post "stores/search" => "stores#search"

  get "home/translate" => "home#translate"

  resources :brands
  resources :abouts
  resources :contacts
  resources :news
  resources :stores
  resources :subscribes
  resources :products
  resources :inspections
  mount Ckeditor::Engine => '/ckeditor'

  namespace :admin do
    root 'home#index'
    resources :site_configs
    resources :site_config_images
    resources :contacts
    resources :news
    resources :brands
    resources :products
    resources :images
    resources :histories
    resources :abouts
    resources :staffs
    resources :stores
    resources :subscribes
    resources :subproducts
  end

  get "home/new_verification" => "home#new_verification"
  post "home/verification" => "home#verification"
  get 'home/terms_of_service'
  get 'home/privacy_policy'
  devise_for :users

  get "brand/:url_name" => "brands#show"
  get "product/:url_name" => "products#show"

  root 'home#index'

end

www/app/models/admin/brand.rb
include ActionView::Helpers::SanitizeHelper
class Admin::Brand < ActiveRecord::Base
	mount_uploader :main_visual, ImageUploader
	mount_uploader :image_of_brand, ImageUploader
	mount_uploader :image_of_logo, ImageUploader
	mount_uploader :main_visual2, ImageUploader
	mount_uploader :og_image, ImageUploader
	has_many :products

	validates_presence_of :url_name

	def get_customization
		if self.is_customization &&self.cn_name.present?
			self.cn_name
		else
			"default"
		end
	end

	def select_name
		'品牌 / ' + self.name.upcase
	end

	def get_short_description_2
		if strip_tags(self.description_2).gsub("&nbsp;", "").gsub("&quot;", "").gsub("&amp;", "").length > 60
			strip_tags(self.description_2).gsub("&nbsp;", "").gsub("&quot;", "").gsub("&amp;", "")[0..60] + '......'
		else
			strip_tags(self.description_2).gsub("&nbsp;", "").gsub("&quot;", "").gsub("&amp;", "")
		end
	end

	def get_og_image
		if self.og_image.present?
			self.og_image.large.url
		else
			self.main_visual.large.url
		end
	end
end

www/app/controllers/admin/brands_controller.rb
class Admin::BrandsController < Admin::ApplicationController
  before_action :set_admin_brand, only: [:show, :edit, :update, :destroy]

  # GET /admin/brands
  # GET /admin/brands.json
  def index
    @admin_brands = Admin::Brand.all.order(:sort)
  end

  # GET /admin/brands/1
  # GET /admin/brands/1.json
  def show
  end

  # GET /admin/brands/new
  def new
    @admin_brand = Admin::Brand.new
  end

  # GET /admin/brands/1/edit
  def edit
  end

  # POST /admin/brands
  # POST /admin/brands.json
  def create
    @admin_brand = Admin::Brand.new(admin_brand_params)

    respond_to do |format|
      if @admin_brand.save
        format.html { redirect_to admin_brands_path, notice: '新增品牌成功' }
        format.json { render :show, status: :created, location: @admin_brand }
      else
        format.html { render :new }
        format.json { render json: @admin_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/brands/1
  # PATCH/PUT /admin/brands/1.json
  def update
    respond_to do |format|
      if @admin_brand.update(admin_brand_params)
        format.html { redirect_to admin_brands_path, notice: '更新品牌成功' }
        format.json { render :show, status: :ok, location: @admin_brand }
      else
        format.html { render :edit }
        format.json { render json: @admin_brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/brands/1
  # DELETE /admin/brands/1.json
  def destroy
    @admin_brand.destroy
    respond_to do |format|
      format.html { redirect_to admin_brands_url, notice: '刪除品牌成功' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_brand
      @admin_brand = Admin::Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_brand_params
      params.require(:admin_brand).permit(:name, :content, :main_visual, :main_visual2, :cn_name, :is_customization, :slogan, :slogan_by, :title_1, :description_1, :title_2, :description_2, :image_of_brand, :image_of_logo, :sort, :is_public, :url_name, :show_products_read_more, :og_title, :og_description, :og_image)
    end
end

www/app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  # layout 'application_static'
  def index
    @title = "BRAND | " + Admin::SiteConfig.first.title
    @admin_brands = Admin::Brand.where(:is_public => true).order(:sort)

    @og_title = Admin::OgMainPage.first.brand_title if Admin::OgMainPage.first.present? && Admin::OgMainPage.first.brand_title.present?
    @og_description = Admin::OgMainPage.first.brand_description if Admin::OgMainPage.first.present? && Admin::OgMainPage.first.brand_description.present?
    @og_image = Admin::OgMainPage.first.brand_image.large.url if Admin::OgMainPage.first.present? && Admin::OgMainPage.first.brand_image.present?
    @og_image2 = Admin::OgMainPage.first.brand_image2.large.url if Admin::OgMainPage.first.present? && Admin::OgMainPage.first.brand_image2.present?
    @og_image3 = Admin::OgMainPage.first.brand_image3.large.url if Admin::OgMainPage.first.present? && Admin::OgMainPage.first.brand_image3.present?
  end

  def show
    if params[:url_name].present?
    	@admin_brand = Admin::Brand.where(:url_name => params[:url_name]).first
    elsif params[:id].present?
    	@admin_brand = Admin::Brand.find(params[:id])
    end

    if @admin_brand.present?
      @title = @admin_brand.name.upcase + " | " + Admin::SiteConfig.first.title
      @meta_description = @admin_brand.description_1

      @og_title = @admin_brand.og_title
      @og_description = @admin_brand.og_description
      @og_image = @admin_brand.get_og_image
    else
      redirect_to root_path
    end
  end
end

www/app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

www/app/views/brands/_brand1.html.erb
<div class='brand1_wrapper'>
	<section class='main_visual'>
		<div class='d_logo_wrapper drop_down_block'>
			<div class='logo'>
					<%= image_tag('logo/w8.png') %>
			</div>
			<div class='down blink_animation' id='arrow'>
				<%= image_tag('arrow.png') %>
			</div>
		</div>
		<% if @admin_brand.main_visual.present? %>
			<%= image_tag(@admin_brand.main_visual.verylarge.url) %>
		<% else %>
			<%= image_tag('brand1_banner_2.png') %>
		<% end %>

	</section>
	<section class='fixed'>
		<div class='brand1_container'>

			<div class='logo'>
				<% if @admin_brand.image_of_logo.present? %>
					<%= image_tag(@admin_brand.image_of_logo.thumb.url) %>
				<% else %>
					<%= image_tag('brand_logo/casamigos.png') %>
				<% end %>
			</div>
			<h1 class='slogan'><%= @admin_brand.slogan %> 
				<% if @admin_brand.slogan_by.present? %>
					<em>– <%= @admin_brand.slogan_by %></em>
				<% end %>
			</h1>
			


			<div class='all_product'>
				<% if @admin_brand.image_of_brand.present? %>
					<%= image_tag(@admin_brand.image_of_brand.url) %>
				<% else %>
					<%= image_tag('brand1_img1.png') %>
				<% end %>
			</div>


			<h3 class=''><%= @admin_brand.title_1 %></h3>
			<p class='detail'><%= @admin_brand.description_1 %></p>

			
			
			<h3 class=''><%= @admin_brand.title_2 %></h3>

			<div class='all_product_detail detail'>
				<div class="short_desciption_2">
					<%= @admin_brand.get_short_description_2 %>
				</div>
				<div class="all_description_2">
					<%= simple_format(@admin_brand.description_2) %>
				</div>
			</div>
			<a class="all_description_2_read_more_button">READ MORE</a>

			
			<header class='product_price'>Product</header>
			
			<section class='products_index'>
				

<%# 2.times do %>
				<% @admin_brand.products.each do |product|  %>
					<article class='product'>
						<section class='product_img'>
							<%= image_tag(product.main_visual.large.url) %>
						</section>
						<section class='product_text'>
							<h1 class='product_name'><%= product.name %>
								<div class='price_block'>
									<!-- <span class='price_title'>PEICE : </span> -->
									<span class='price'>$<%= product.price %> NTD</span>
								</div>
							 </h1>

							<p class='product_description'>
								<%= product.title %>
							</p>
							<div class='product_detail'>
								<%= simple_format(product.content.gsub(/\r\n?/,"") ) %>
							</div>

							<div class='buttom_block'>
								<% if product.url_name.present? %>
									<a href='<%= "/product/#{product.url_name}" %>' class='buttom product_read_more'>
										READ MORE >>
									</a>
								<% else %>
									<a href='<%= product_path(product.id) %>' class='buttom product_read_more'>
										READ MORE >>
									</a>
								<% end %>
								<a href='<%= stores_path(:product_id => product.id) %>' class='buttom' data-no-turbolink>
									WHERE TO BUY ?
								</a>
							</div>


						</section>
					</article>
				<% end %>



				<!-- <article class='product'>
					<section class='product_img'>
						<%= image_tag('brand1_tmp/c1.png') %>
					</section>
					<section class='product_text'>
						<h1 class='product_name'>Blanco
							<div class='price_block'>
								<span class='price'>$2380 NTD</span>
							</div>
						 </h1>

						<p class='product_description'>
							純淨代表作品。蒸餾製程後靜置兩個月才裝瓶。輕盈順滑的口感，淺淺的柑橘、香草、和龍舌蘭本身的甘甜香味，無論純飲或調酒皆為入門首選。
						</p>
						<div class='product_detail'>
							<ul>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
							</ul>
						</div>

						<div class='buttom_block'>
							<a href='#' class='buttom'>
								READ MORE >>
							</a>
							<a href='#' class='buttom'>
								WHERE TO BUY ?
							</a>
						</div>


					</section>
				</article>






				<article class='product'>
					<section class='product_img'>
						<%= image_tag('brand1_tmp/c2.png') %>
					</section>
					<section class='product_text'>
						<h1 class='product_name'>Blanco
							<div class='price_block'>
								<span class='price'>$2380 NTD</span>
							</div>
						 </h1>

						<p class='product_description'>
							純淨代表作品。蒸餾製程後靜置兩個月才裝瓶。輕盈順滑的口感，淺淺的柑橘、香草、和龍舌蘭本身的甘甜香味，無論純飲或調酒皆為入門首選。
						</p>
						<div class='product_detail'>
							<ul>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
							</ul>
						</div>

						<div class='buttom_block'>
							<a href='#' class='buttom'>
								READ MORE >>
							</a>
							<a href='#' class='buttom'>
								WHERE TO BUY ?
							</a>
						</div>


					</section>
				</article> -->

<%# end %>				
			</section>


		</div>


	</section>
	<%= render :partial => 'shared/where_block' %>
	
</div>

<script type="text/javascript">
	  
	  $(document).ready(function(){

	  	var body = $("html, body");
	  	var to_show_height =$(window).height()-($(window).height()*0.2)
	  	$('.drop_down_block').click(function(event) {
	  		body.animate({scrollTop:to_show_height}, '1500', 'swing', function() { 
			   
			});
	  	});
	  	
	  	if ($(window).width() > 768) {
		  	$("article.product section.product_text").each(function() {
		  		if ($(this).height() < $(this).parent().find(".product_img").height()){
			  		$(this).height($(this).parent().find(".product_img").height());
		  		}else{
		  			$(this).height($(this).height()+130);
		  		}

			});
	  	}
		$(window).resize(function(){
		  	if ($(window).width() < 768) {
	  			$("article.product section.product_text").each(function() {
				  $(this).height("");
				});
		  	}else {
			  	$("article.product section.product_text").each(function() {
				  	$(this).height($(this).parent().find(".product_img").height());
				});
		  	}
		});

		$(".all_description_2_read_more_button").click(function() {
			// $(".all_description_2").show();

			$(".all_description_2").slideDown(600, function() {
				$(".all_description_2").show();
			});    
			$(this).hide();
			$(".short_desciption_2").hide();
		});
	  });
</script>

www/app/views/brands/_brand2.html.erb
<div class='brand2_wrapper'>
	<section class='main_visual'>
		<div class='logo_wrapper'>
			<div class='logo'>
				<% if @admin_brand.image_of_logo.present? %>
					<%= image_tag(@admin_brand.image_of_logo.thumb.url) %>
				<% else %>
					<%= image_tag('brand_logo/casamigos.png') %>
				<% end %>
			</div>
		</div>
		<div class='d_logo_wrapper drop_down_block'>
			<div class='logo'>
					<%= image_tag('logo/w8.png') %>
			</div>
			<div class='down blink_animation' id='arrow'>
				<%= image_tag('arrow.png') %>
			</div>
		</div>
		<% if @admin_brand.main_visual.present? %>
			<%= image_tag(@admin_brand.main_visual.verylarge.url) %>
		<% else %>
			<%= image_tag('brand1_banner_2.png') %>
		<% end %>	

	</section>
	<section class='fixed'>
		<div class='brand2_container'>
			
			<!-- <div class='products_menu'> -->
				<!-- <div class='logo'>
					<%= image_tag(@admin_brand.image_of_logo.thumb.url) %>
				</div> -->
				<!-- <div class='menu_item'>
					Maynmar Beer
					<span class='cc'>
						330cc
					</span>
				</div>
				<div class='menu_item'>
					Maynmar Beer
					<span class='cc'>
						640cc 
					</span>
				</div> -->
			<!-- </div> -->

			<h1 class='slogan'><%= @admin_brand.slogan %> 
				<% if @admin_brand.slogan_by.present? %>
					<em>– <%= @admin_brand.slogan_by %></em>
				<% end %>
				<%= image_tag(@admin_brand.image_of_logo.small.url) %>
			</h1>
			<h3 class=''><%= @admin_brand.title_1 %></h3>
			<p class='detail'><%= @admin_brand.description_1 %></p>
			


			<div class='all_product'>
				<% if @admin_brand.image_of_brand.present? %>
					<%= image_tag(@admin_brand.image_of_brand.url) %>
				<% else %>
					<%= image_tag('brand1_img1.png') %>
				<% end %>

				<!-- <div class='detail'>
					<div class='detail_item'>
						<ul>
							<li>產地：緬甸</li>
							<li>酒精：5 %</li>
							<li>容量：640ml(瓶裝)</li>
						</ul>
					</div>
					<div class='detail_item'>
						<ul>
							<li>產地：緬甸</li>
							<li>酒精：5 %</li>
							<li>容量：330ml(罐裝)</li>
						</ul>
					</div>
				</div> -->
			</div>
			
			<hr />

			
			
<!-- 			<h3 class=''><%= @admin_brand.title_2 %></h3>

			<div class='all_product_detail detail'>
				<%= simple_format(@admin_brand.description_2) %>
			</div>
 -->
			
			
			
<section class='products_index'>
				

<%# 2.times do %>
				<% @admin_brand.products.each do |product|  %>
					<article class='product'>
						<section class='product_img'>
							<%= image_tag(product.main_visual.large.url) %>
						</section>
						<section class='product_text'>
							<h1 class='product_name'><%= product.name %>
								<div class='price_block'>
									<!-- <span class='price_title'>PEICE : </span> -->
									<span class='price'>$<%= product.price %> NTD</span>
								</div>
							 </h1>

							<!-- <p class='product_description'>
								<%= product.title %>
							</p> -->
							<div class='product_detail'>
								<%= simple_format(product.content.gsub(/\r\n?/,"") ) %>
							</div>

							<div class='buttom_block'>
								<a href='<%= product_path(product.id) %>' class='buttom product_read_more'>
									READ MORE >>
								</a>
								
								<a href='<%= stores_path(:product_id => product.id) %>' class='buttom' data-no-turbolink>
									WHERE TO BUY ?
								</a>
							</div>


						</section>
					</article>
				<% end %>



				<!-- <article class='product'>
					<section class='product_img'>
						<%= image_tag('brand1_tmp/c1.png') %>
					</section>
					<section class='product_text'>
						<h1 class='product_name'>Blanco
							<div class='price_block'>
								<span class='price'>$2380 NTD</span>
							</div>
						 </h1>

						<p class='product_description'>
							純淨代表作品。蒸餾製程後靜置兩個月才裝瓶。輕盈順滑的口感，淺淺的柑橘、香草、和龍舌蘭本身的甘甜香味，無論純飲或調酒皆為入門首選。
						</p>
						<div class='product_detail'>
							<ul>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
							</ul>
						</div>

						<div class='buttom_block'>
							<a href='#' class='buttom'>
								READ MORE >>
							</a>
							<a href='#' class='buttom'>
								WHERE TO BUY ?
							</a>
						</div>


					</section>
				</article>






				<article class='product'>
					<section class='product_img'>
						<%= image_tag('brand1_tmp/c2.png') %>
					</section>
					<section class='product_text'>
						<h1 class='product_name'>Blanco
							<div class='price_block'>
								<span class='price'>$2380 NTD</span>
							</div>
						 </h1>

						<p class='product_description'>
							純淨代表作品。蒸餾製程後靜置兩個月才裝瓶。輕盈順滑的口感，淺淺的柑橘、香草、和龍舌蘭本身的甘甜香味，無論純飲或調酒皆為入門首選。
						</p>
						<div class='product_detail'>
							<ul>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
								<li>
									<span class='title'>AGAVE :</span>
									100% Highland Blue Agave, aged 7-9 years, hand cut
								</li>
							</ul>
						</div>

						<div class='buttom_block'>
							<a href='#' class='buttom'>
								READ MORE >>
							</a>
							<a href='#' class='buttom'>
								WHERE TO BUY ?
							</a>
						</div>


					</section>
				</article> -->

<%# end %>				
			</section>


		</div>


	</section>
		<section class='main_visual'>
			
			<% if @admin_brand.main_visual2.present? %>
				<%= image_tag(@admin_brand.main_visual2.verylarge.url) %>
			<% else %>
				<%= image_tag('banner8.jpg') %>
			<% end %>
		</section>

	<%= render :partial => 'shared/where_block' %>
	
</div>

<script type="text/javascript">
	  
	  $(document).ready(function(){



	  	var body = $("html, body");
	  	var to_show_height =$(window).height()-($(window).height()*0.1)
	  	$('.drop_down_block').click(function(event) {
	  		body.animate({scrollTop:to_show_height}, '1500', 'swing', function() { 
			   
			});
	  	});

	  	
	  	if ($(window).width() > 768) {
		  	$("article.product section.product_text").each(function() {
		  		if ($(this).height() < $(this).parent().find(".product_img").height()){
			  		$(this).height($(this).parent().find(".product_img").height());
		  		}else{
		  			$(this).height($(this).height()+130);
		  		}

			});
	  	}
		$(window).resize(function(){
		  	if ($(window).width() < 768) {
	  			$("article.product section.product_text").each(function() {
				  $(this).height("");
				});
		  	}else {
			  	$("article.product section.product_text").each(function() {
				  	$(this).height($(this).parent().find(".product_img").height());
				});
		  	}
		});
	  });
</script>

www/app/views/brands/_default.html.erb
default

www/app/views/brands/index.html.erb
<div class="brand_wrapper">
	<section class="fixed">
		<h1>OUR BRANDS</h1>
		<% if @admin_brands.present? %>
			<% @admin_brands.each do |brand| %>
				<a href="<%= "/brand/#{brand.url_name}" %>" data-no-turbolink>
					<section>
						
						
						<div class="logo">
							<%= image_tag(brand.image_of_logo.thumb.url) %>
						</div>
						<h1 class='brand_name'><%= brand.name %></h1>
						
						
						<%#= link_to("Show",brand_path(brand.id),:class => "button") %>
					</section>
				</a>
			<% end %>

			<% if @admin_brands.count % 2 != 0 %>
				<section class="coming_soon">
					<!-- <div class="logo">
						<span>COMING SOON...</span>
					</div> -->
					<div class="logo">
						<%= image_tag("c1.jpg") %>
					</div>
					<h1 class='brand_name'>即將上市</h1>
				</section>
			<% end %>
		<% end %>
	</section>
</div>

www/app/views/brands/show.html.erb
<%= render :partial => @admin_brand.get_customization %>

<% if !@admin_brand.show_products_read_more %>
	<script type="text/javascript">
		$.each( $(".product_read_more"), function(){
			$(this).hide();
		});
	</script>
<% end %>